# =================================================
# Fluent-Bit 서비스 전역 행동 설정
# 수집 -> 전처리/추출 X -> 적재(배달)
# logstash 연계 없다면 여기서 전처리/필터링 등 작업 수행
# =================================================
[SERVICE]
    Flush       1       # 수집된 데이터를 몇 초 간격으로 출력할(내보낼) 것인가 설정, 1: 1초마다 데이터 전송(실시간성)
    Log_Level   info    # Fluent-Bit 로그에 대한 레벨 설정 (error, warn, info, debug), info: 실행 정보, debug

# =================================================
# 데이터 수집 Input: 어디서 데이터 가져올 것인가
# Input: sensor_json.log
# =================================================
[INPUT]
    Name    tail                                        # 파일 끝에서 읽어옴: 플러그인
    Path    /opt/airflow/sensor_logs/sensor_json.log    # 읽어올 로그 파일 경로 -> 날짜 변경/파일 커지면 해결법 고민 필요
    Tag     sensor_json                                 # 해당 데이터에 tag 표시, 차후 [Output]에서 태크를 보고 어디로 전송할지 필터링
    Parser  json                                        # 파일 내용을 미리 정의된 json 파서를 활용하여 구조화된 데이터로 인식 -> 후속 작업은 없음

# =================================================
# Input: sensor_text.log
# =================================================
# [INPUT]
#     Name    tail
#     Path    /opt/airflow/sensor_logs/sensor_text.log
#     Tag     sensor.text

# =================================================
# 데이터 배포 Output: 어디로 데이터 보낼 것인가
# Output: Kafka
# =================================================
[OUTPUT]
    # Kafka출력 플러그인
    Name    Kafka
    # tag가 sensor.json인 데이터만 출력 설정 -> 필터링
    Match   sensor.json
    # 전송할 곳 엔드포인트(kafka의 브로커의 주소)
    # (도커 컴포즈 구성시 서비스명): 포트 -> AWS MSK의 엔드포인트로 교체
    Brokers kafka:9092
    # 데이터를 카프카로 보낼 때 토픽명 필요
    Topics  factory-json-topic
    # 전송되는 데이터 형식 -> JSON 형태 유지
    Format  json


# =================================================
# Output: logstash (http로 전송)
# =================================================
[OUTPUT]